####################################
#  update for 2022/07/25 00:28:42  #
####################################
name: ç¼–è¯‘å›ºä»¶_immortalwrt

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      resource_directory:
        type: choice
        description: 'è·¯ç”±å™¨èµ„æºç›®å½•'
        options:
          - "P2W_R619AC-128M"
          - "XIAOMI-4A_100M"
          - "XIAOMI-4A_GIGABit"
          - "XIAOMI-CR660X"
          - "redmi-ac2100"
      repo_branch:
        type: choice
        description: 'ç‰ˆæœ¬åˆ†æ”¯'
        options:
          - "master"
          - "openwrt-18.06"
          - "openwrt-18.06-k5.4"
          - "openwrt-21.02"
      feeds_file:
        type: choice
        description: 'æ›¿æ¢è½¯ä»¶æºé…ç½®(feeds.conf.default)'
        options:
        - "true"
        - "false"
      config_file:
        description: 'config æ–‡ä»¶åç§°(.config)'
        default: 'immortalwrt.config'
      files_path:
        type: choice
        description: 'å¯¼å…¥è¡¥ä¸ç›®å½•(filesç›®å½•)'
        options:
        - "true"
        - "false"
      openwrt_patch:
        type: choice
        description: 'æ‰§è¡Œä»“åº“è„šæœ¬(make_patch.sh)'
        options:
        - "true"
        - "false"
      befor_patch:
        type: choice
        description: 'æ‰§è¡Œç¼–è¯‘å‰è„šæœ¬(make_befor.sh)'
        options:
        - "true"
        - "false"
      after_patch:
        type: choice
        description: 'æ‰§è¡Œç¼–è¯‘åè„šæœ¬(make_after.sh)'
        options:
        - "true"
        - "false"
      upload_release:
        type: choice
        description: 'å‘å¸ƒåˆ°release'
        options:
        - "false"
        - "true"
env:
  TIMEZONE: Asia/Shanghai
  
  UPLOAD_ACTIONSRUNS: true
  
  Resoure_DIR: ${{ github.event.inputs.resource_directory }}
  
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: ${{ github.event.inputs.repo_branch }}
  RELEASE_TAG: immortalwrt
  CONFIG_FILE: '${{ github.event.inputs.resource_directory }}/${{ github.event.inputs.config_file }}'
  FEEDS_FILE: '${{ github.event.inputs.resource_directory }}/immortalwrt.feeds'
  REPLACE_FEEDS: ${{ github.event.inputs.feeds_file }}
  LOAD_FILES: ${{ github.event.inputs.files_path }}
  FILES_PATH: '${{ github.event.inputs.resource_directory }}/files'
  RUN_OPENWRTPATCH: ${{ github.event.inputs.openwrt_patch }}
  OPENWRT_PATCH: '${{ github.event.inputs.resource_directory }}/build_patch.sh'
  RUN_BEFORPATCH: ${{ github.event.inputs.befor_patch }}
  BEFOR_PATCH: '${{ github.event.inputs.resource_directory }}/immortalwrt_befor.sh'
  RUN_AFTERPATCH: ${{ github.event.inputs.after_patch }}
  AFTER_PATCH: '${{ github.event.inputs.resource_directory }}/build_after.sh'
  UPLOAD_RELEASE: ${{ github.event.inputs.upload_release }}


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: æ£€å‡ºä»“åº“æ•°æ®
      uses: actions/checkout@main

    - name: åˆå§‹ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
        #éäº¤äº’å¼ç¯å¢ƒ
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TIMEZONE"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: æå–ç³»ç»Ÿä¿¡æ¯
      working-directory: /workdir
      run: |
         echo -e "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
         echo -e "UserName: $(whoami) \n"
         echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB') \n"

    - name: æ‹‰å–æºç ä»“åº“
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: æ£€æŸ¥æ–‡ä»¶çŠ¶æ€
      id: check
      run: |
        [ -e $FEEDS_FILE ] && echo "::set-output name=feeds::success"
        [ -e $FILES_PATH ] && echo "::set-output name=files::success"
        [ -e $OPENWRT_PATCH ] && echo "::set-output name=patch::success"
        [ -e $BEFOR_PATCH ] && echo "::set-output name=befor::success"
        [ -e $AFTER_PATCH ] && echo "::set-output name=after::success"
        echo "é…ç½®æ–‡ä»¶è·¯å¾„"
        [ -e $FEEDS_FILE ] && echo $FEEDS_FILE
        [ -e $FILES_PATH ] && echo $FILES_PATH
        [ -e $OPENWRT_PATCH ] && echo $OPENWRT_PATCH
        [ -e $BEFOR_PATCH ] && echo $BEFOR_PATCH
        [ -e $AFTER_PATCH ] && echo $AFTER_PATCH

    - name: æ›¿æ¢è½¯ä»¶æºé…ç½®
      if: env.REPLACE_FEEDS == 'true' && steps.check.outputs.feeds == 'success'
      run: |
        [ -e $FEEDS_FILE ] && rm -f openwrt/feeds.conf.default
        [ -e $FEEDS_FILE ] && mv $FEEDS_FILE openwrt/feeds.conf.default

    - name: å¯¼å…¥è¡¥ä¸ç›®å½•
      if: env.LOAD_FILES == 'true' && steps.check.outputs.files == 'success'
      run: mv $FILES_PATH openwrt/files

    - name: æ‰§è¡Œä»“åº“è„šæœ¬
      if: env.RUN_OPENWRTPATCH == 'true' && steps.check.outputs.patch == 'success'
      run: |
        chmod +x $OPENWRT_PATCH
        cd openwrt
        $GITHUB_WORKSPACE/$OPENWRT_PATCH

    - name: æ›´æ–°å¹¶å®‰è£…è½¯ä»¶æº
      run: |
        cd openwrt 
        ./scripts/feeds update -a && ./scripts/feeds install -a
        ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: åŠ è½½å›ºä»¶é…ç½®
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cat openwrt/.config

    - name: æ‰§è¡Œç¼–è¯‘è„šæœ¬(å‰)
      if: env.RUN_BEFORPATCH == 'true' && steps.check.outputs.befor == 'success'
      run: |
        chmod +x $BEFOR_PATCH
        cd openwrt
        ls
        $GITHUB_WORKSPACE/$BEFOR_PATCH

    - name: ä¸‹è½½ç¼–è¯‘ dl åº“
      id: makedownload
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ç¼–è¯‘å›ºä»¶
      id: makefirmware
      run: |
        cd openwrt
        echo -e "$(nproc) thread cpu"
        echo "Start Time: "$(date +"%Y/%m/%d %H:%M:%S")""
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "End Time: "$(date +"%Y/%m/%d %H:%M:%S")""
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: æ‰§è¡Œç¼–è¯‘è„šæœ¬(å)
      if: env.RUN_AFTERPATCH == 'true' && steps.check.outputs.after == 'success'
      run: |
        chmod +x $AFTER_PATCH
        cd openwrt
        $GITHUB_WORKSPACE/$AFTER_PATCH

    - name: æ•´ç†æ–‡ä»¶
      id: organize
      if: steps.makefirmware.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages feeds.buildinfo sha256sums version.buildinfo
        cp ../../../../.config ./build.config
        cp ../../../../feeds.conf.default ./feeds.conf.default
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: ä¸Šä¼ å›ºä»¶åˆ°artifact
      uses: actions/upload-artifact@main
      if: env.UPLOAD_ACTIONSRUNS == 'true' && steps.organize.outputs.status == 'success'
      with:
        name: ${{ env.RELEASE_TAG }}_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: æ¸…ç†è¿è¡Œæ—§æ•°æ®
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 5

    - name: ç”Ÿæˆreleaseæ ‡ç­¾
      id: releasetag
      if: env.UPLOAD_RELEASE == 'true' && steps.makefirmware.outputs.status == 'success' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M-(${{ env.RELEASE_TAG }}${{ env.DEVICE_NAME }})")"
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "ğŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "ğŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "- â­ï¸ä¸ªäººç²¾ç®€ $RELEASE_TAGï¼šSSR, KMS, UPNP, TURBO ACC" >> release.txt
        echo "- ğŸ”¥é»˜è®¤IPï¼š192.168.3.1 é»˜è®¤å¯†ç ï¼špassword" >> release.txt
        echo "- æºç :ã€æŸ¥çœ‹[â¦$REPO_URL]($REPO_URL)æ›´æ–°è®°å½•ã€‘" >> release.txt
        echo "- ç¼–è¯‘æ—¶é—´ï¼š$(date +"%Y.%m.%d-%H%M")" >> release.txt
        echo "::set-output name=status::success"

    - name: ä¸Šä¼ å›ºä»¶åˆ°Release
      uses: softprops/action-gh-release@v1
      if: env.UPLOAD_RELEASE == 'true' && steps.releasetag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.releasetag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: æ¸…ç†Releasesæ—§æ•°æ®
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
